build:
  tests:
    before:
      - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
      - bash initial.sh
    override:
      -
        command: "vendor/bin/codecept run --coverage-xml"
        coverage:
          file: 'tests/_output/coverage.xml'
          format: 'clover'
  environment:
    php: 7.0
    mysql: 5.6
checks:
  php: true
filter:
  excluded_paths:
    - tests/
